package xtensus.stage.GReclamation.entities;

// Generated 14 f�vr. 2013 15:57:20 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Appeloffre generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer"})
@Entity
@Table(name = "appeloffres")
public class Appeloffre  implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4993608869249442164L;
	private Integer appelOffreReference;

	private String appelOffreCode;
	private String appelOffreIntitule;
	private String appelOffreObjet;
	private Date appelOffreDatePublication;
	private Date appelOffreDateLimiteRemise;
	private Date appelOffreDateLimiteRetrait;
	private Date appelOffreDateSeanceOuverturePlis;
	private Float appelOffreCoutEstime;
	private Float appelOffrePrixDoc;
	private Integer appelOffreNbrLots;
	private int realisationId;
	private String appelOffreAvis;
	private String detailsAnnulation;
//	private Set<Soumissionnaire> soumissionnaires = new HashSet<Soumissionnaire>(
//			0);
	

	public Appeloffre() {
	}

	public Appeloffre(
			String appelOffreCode, String appelOffreIntitule,
			String appelOffreObjet, Date appelOffreDatePublication,
			Date appelOffreDateLimiteRemise, Date appelOffreDateLimiteRetrait,
			Date appelOffreDateSeanceOuverturePlis, Float appelOffreCoutEstime,
			Integer appelOffreNbrLots,Float appelOffrePrixDoc, Set<Soumissionnaire> soumissionnaires) {
		
		this.appelOffreCode = appelOffreCode;
		this.appelOffreIntitule = appelOffreIntitule;
		this.appelOffreObjet = appelOffreObjet;
		this.appelOffreDatePublication = appelOffreDatePublication;
		this.appelOffreDateLimiteRemise = appelOffreDateLimiteRemise;
		this.appelOffreDateLimiteRetrait = appelOffreDateLimiteRetrait;
		this.appelOffreDateSeanceOuverturePlis = appelOffreDateSeanceOuverturePlis;
		this.appelOffreCoutEstime = appelOffreCoutEstime;
		this.appelOffreNbrLots = appelOffreNbrLots;
		this.appelOffrePrixDoc=appelOffrePrixDoc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "appeloffresId", unique = true, nullable = false)
	public Integer getAppelOffreReference() {
		return this.appelOffreReference;
	}

	public void setAppelOffreReference(Integer appelOffreReference) {
		this.appelOffreReference = appelOffreReference;
	}

	

	

	
	
	@Column(name = "appelOffreCode", length = 254)
	public String getAppelOffreCode() {
		return this.appelOffreCode;
	}

	public void setAppelOffreCode(String appelOffreCode) {
		this.appelOffreCode = appelOffreCode;
	}

	@Column(name = "appelOffreIntitule", length = 254)
	public String getAppelOffreIntitule() {
		return this.appelOffreIntitule;
	}

	public void setAppelOffreIntitule(String appelOffreIntitule) {
		this.appelOffreIntitule = appelOffreIntitule;
	}

	@Column(name = "appelOffreObjet", length = 254)
	public String getAppelOffreObjet() {
		return this.appelOffreObjet;
	}

	public void setAppelOffreObjet(String appelOffreObjet) {
		this.appelOffreObjet = appelOffreObjet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "appelOffreDatePublication", length = 10)
	public Date getAppelOffreDatePublication() {
		return this.appelOffreDatePublication;
	}

	public void setAppelOffreDatePublication(Date appelOffreDatePublication) {
		this.appelOffreDatePublication = appelOffreDatePublication;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "appelOffreDateLimiteRemise", length = 10)
	public Date getAppelOffreDateLimiteRemise() {
		return this.appelOffreDateLimiteRemise;
	}

	public void setAppelOffreDateLimiteRemise(Date appelOffreDateLimiteRemise) {
		this.appelOffreDateLimiteRemise = appelOffreDateLimiteRemise;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "appelOffreDateLimiteRetrait", length = 10)
	public Date getAppelOffreDateLimiteRetrait() {
		return this.appelOffreDateLimiteRetrait;
	}

	public void setAppelOffreDateLimiteRetrait(Date appelOffreDateLimiteRetrait) {
		this.appelOffreDateLimiteRetrait = appelOffreDateLimiteRetrait;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "appelOffreDateSeanceOuverturePlis", length = 10)
	public Date getAppelOffreDateSeanceOuverturePlis() {
		return this.appelOffreDateSeanceOuverturePlis;
	}

	public void setAppelOffreDateSeanceOuverturePlis(
			Date appelOffreDateSeanceOuverturePlis) {
		this.appelOffreDateSeanceOuverturePlis = appelOffreDateSeanceOuverturePlis;
	}

	@Column(name = "appelOffreCoutEstime", precision = 12, scale = 0)
	public Float getAppelOffreCoutEstime() {
		return this.appelOffreCoutEstime;
	}

	public void setAppelOffreCoutEstime(Float appelOffreCoutEstime) {
		this.appelOffreCoutEstime = appelOffreCoutEstime;
	}

	@Column(name = "appelOffreNbrLots")
	public Integer getAppelOffreNbrLots() {
		return this.appelOffreNbrLots;
	}

	public void setAppelOffreNbrLots(Integer appelOffreNbrLots) {
		this.appelOffreNbrLots = appelOffreNbrLots;
	}

//	@ManyToMany(fetch = FetchType.LAZY)
//	@JoinTable(name = "appeloffresoumissionnaire", joinColumns = { @JoinColumn(name = "appelOffreReference", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "soumissionnaireReference", nullable = false, updatable = false) })
//	public Set<Soumissionnaire> getSoumissionnaires() {
//		return this.soumissionnaires;
//	}
//
//	public void setSoumissionnaires(Set<Soumissionnaire> soumissionnaires) {
//		this.soumissionnaires = soumissionnaires;
//	}

	

	
	
	@Column(name = "appelOffrePrixDoc")
	public Float getAppelOffrePrixDoc() {
		return appelOffrePrixDoc;
	}

	public void setAppelOffrePrixDoc(Float appelOffrePrixDoc) {
		this.appelOffrePrixDoc = appelOffrePrixDoc;
	}
	@Column(name = "realisationId")
	public int getRealisationId() {
		return realisationId;
	}

	public void setRealisationId(int realisationId) {
		this.realisationId = realisationId;
	}
	
	@Column(name = "detailsAnnulation")
	public String getDetailsAnnulation() {
		return detailsAnnulation;
	}

	public void setDetailsAnnulation(String detailsAnnulation) {
		this.detailsAnnulation = detailsAnnulation;
	}

	@Column(name = "appelOffreAvis")
	public String getAppelOffreAvis() {
		return appelOffreAvis;
	}

	public void setAppelOffreAvis(String appelOffreAvis) {
		this.appelOffreAvis = appelOffreAvis;
	}
}
